image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 5900
  - port: 6080
    onOpen: notify
  - port: 35900

tasks:
  - before: nvm install 12 && nvm alias default 12
  - init: npm install
  - command: npm run dev:gitpod
  - command: npm run build-watch

vscode:
  extensions:
    - wayou.vscode-todo-highlight@1.0.4:8IqxuxCVol2WnScJc5xVzg==
    - msjsdiag.debugger-for-chrome@4.12.2:OgS8bhPr0xhAeewS3vg4Qw==