name: Build binaries and package

on: [push, pull_request]

jobs:
  windows_build:
    name: Windows Latest Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: "Restore npm cache"
        uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: npm install
        run: npm install
      - name: Package application with electron-builder
        run: npm run pack
      - name: Publish artificats
        uses: actions/upload-artifact@master
        with:
          name: windows-build
          path: dist/win-unpacked
  macos_build:
    name: MacOS Latest Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Restore npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: npm install
        run: npm install
      - name: Package application with electron-builder
        run: npm run pack
      - name: Publish artificats
        uses: actions/upload-artifact@master
        with:
          name: macos-build
          path: dist/mac
