name: Lint

on: [push, pull_request]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint
        run: npx --package eslint --package @typescript-eslint/parser --package @typescript-eslint/eslint-plugin eslint src/ --ext .ts,.tsx --fix
